version: '2'
networks:
  basic: null
services:
  couchdb:
    container_name: couchdb
    image: 'couchdb:2.3'
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - '5984:5984'
    networks:
      - basic
